version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      terraform:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      docker:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns: ["*"]
